Hero Graph remove old block for new block
tari-project/block-explorer-frontend pull request #101
Opened 2020-06-23 13:01 UTC by msbodetti

### Description
When the explorer is opened, new blocks will keep rolling in and the graph becomes unreadable.
### Screencast
https://share.getcloudapp.com/E0uzYYjj

2020-06-23 13:58 UTC, Krakaw requested changes
Don't modify data in a render. Move this to the redux action. Add an env for `MAX_BLOCKS` and if latestBlocks > MAX_BLOCKS then splice off the last.

2020-06-23 14:19 UTC, msbodetti commented
> Don't modify data in a render. Move this to the redux action. Add an env for `MAX_BLOCKS` and if latestBlocks > MAX_BLOCKS then splice off the last.

Thanks @Krakaw. I've moved it to the API call.

2020-06-23 14:28 UTC, Krakaw requested changes

2020-06-23 14:28 UTC, Krakaw commented on src/config.ts
> +    maxBlocks: +(process.env.REACT_APP_MAX_BLOCKS || 100)
Add the env to the .env.sample file

2020-06-23 14:28 UTC, Krakaw commented on src/helpers/api.ts
> +    }
Move this to the redux action. Also how do we know that we only need to reduce by 1? We could've fetched 200 blocks.

2020-10-18 08:21 UTC, delta1 commented
@msbodetti any chance you could please take care of @Krakaw's feedback? Then I'll get this approved and merged - it's a definite improvement!

2020-10-18 09:39 UTC, msbodetti commented
> @msbodetti any chance you could please take care of @Krakaw's feedback? Then I'll get this approved and merged - it's a definite improvement!

Hey @delta1 went off my radar. Let me look at it today! I'll try get something up later today or this week!

2020-10-18 10:48 UTC, delta1 commented
Awesome thanks! There's no rush 🙏

2021-03-01 09:18 UTC, closed without merging