Network Difficulty Graph
tari-project/block-explorer-frontend pull request #28
Opened 2020-06-02 16:42 UTC by msbodetti

2020-06-02 17:32 UTC, Krakaw requested changes
I can't find the X-Axis? Also please add a screenshot to the PR.

2020-06-03 18:32 UTC, Krakaw requested changes
It's close, it needs the shaded area underneath the line graph and use the block heights for the X-Axis.

Let's also decouple these graphs from the data, move the api call to `App.tsx` and pass the data in as a prop.

2020-06-04 15:45 UTC, msbodetti commented
Hi @Krakaw please see recording with tooltip and shaded area on the x axis https://share.getcloudapp.com/v1ueK7Yq

2020-06-08 08:19 UTC, Krakaw requested changes
The component graphs seem to be very tightly coupled to their respective data. If this is the case they should be split out into something like `EstimatedHashGraph` instead of `PolygonGraph`. The best scenario would be extending the PolygonGraph with custom data so we could re-use it in the future.

2020-06-08 08:19 UTC, Krakaw commented on src/App.tsx
> +            });
You can move this into its own `useEffect` block

2020-06-08 08:19 UTC, Krakaw commented on src/api.ts
> +const apiURL: string = process.env.REACT_APP_EXPLORER_API_URL || "";
Is this a duplicate from an old merge? Please merge development back into your branch.

2020-06-08 08:33 UTC, msbodetti commented
> The component graphs seem to be very tightly coupled to their respective data. If this is the case they should be split out into something like `EstimatedHashGraph` instead of `PolygonGraph`. The best scenario would be extending the PolygonGraph with custom data so we could re-use it in the future.

Thanks @Krakaw, should I also do this for the Bar graph chart?

2020-06-08 08:34 UTC, Krakaw commented
> > The component graphs seem to be very tightly coupled to their respective data. If this is the case they should be split out into something like `EstimatedHashGraph` instead of `PolygonGraph`. The best scenario would be extending the PolygonGraph with custom data so we could re-use it in the future.
> 
> Thanks @Krakaw, should I also do this for the Bar graph chart?

Yup.

2020-06-09 12:23 UTC, Krakaw approved these changes

2020-06-09 12:24 UTC, merged